AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**

Documentation:
    Enabled: false

IndentationConsistency:
  Enabled: false

LineLength:
  Max: 90

# Offence count: 1
# Cop supports --auto-correct.
NumericLiterals:
  MinDigits: 14

# Offence count: 3
# Cop supports --auto-correct.
SpaceInsideParens:
  Enabled: false

# Offence count: 97
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
StringLiterals:
  Enabled: false

# Offence count: 7
# Cop supports --auto-correct.
TrailingWhitespace:
  Enabled: false

